apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: melotic-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: melotic-web
    spec:
      containers:
        - name: melotic-web
          image: 569325332953.dkr.ecr.us-east-1.amazonaws.com/melotic-web:__TAG__
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: melotic-web-secrets
            - configMapRef:
                name: melotic-web-configmap
          ports:
            - containerPort: 3001
